-generar una secuencia con departamentos
---------------secuencia para departamentos
--crear un objeto
select * from dept;
create sequence SEQ_DEPT
increment by 10  
start with 40;
-- una secuencia no se puede modificar , solo eliminar y crear de nuevo
--todavia no hemos utilizado  la secuencia
select seq_dept.nextval as SIGUIENTE  from dual;
--no podemos acceder a currval hasta que no hemos ejecutado NEXTVAL
select seq_dept.CURRVAL as ACTUAL  from dual;
-- AÑADIR EL REGISTRO CON EL OBJETO DE SECUENCIA CREADO
INSERT INTO DEPT values (seq_dept.nextval, 'NUEVO', 'NUIEVO'); 
UNA SECUENCIA NO ESTA ASOCIADA A UNA TABLA
SELECT * FROM DEPT
ORDER BY DEPT_NO;
--DELETE FROM DEPT WHERE DEPT_NO = 50; 
--ELIMINAR UNA SECUENCIA
DROP SEQUENCE SEQ_DEPT;
--SE PUEDE EJECUTAR EL OBJETO CON OTRA TABLA
INSERT INTO HOSPITAL VALUES (SEQ_DEPT.NEXTVAL, 'EL CARMEN', 'CALLE PEX', '12345', 125);
SELECT * FROM HOSPITAL;
--NECESITO LAS SIGUIENTE CARACTERISTICAS DENTRO DE NUESTRA BASE DE DATOS
--UNA CLAVE PRIMARIA EN HOSPITAL   PK_EN_HOSPITAL
--UNA CLAVE PRIMARIA EN DOCTOR     PK_EN_DOCTOR
--NECESITO RELACIONAR DOCTORES CON HOSPITALES
--LAS PERSONAS DE LA  TABLA PLANTILLA SOLAMENTE PUEDEN TRABAJAR EN
--TURNOS DE MAÑANA, TARDE O NOCHE (T,N,M)  
--
--UNA CLAVE PRIMARIA EN HOSPITAL   PK_EN_HOSPITAL
ALTER TABLE HOSPITAL
ADD CONSTRAINT PK_HOSPITAL
PRIMARY KEY (HOSPITAL_COD);
--
--UNA CLAVE PRIMARIA EN DOCTOR     PK_EN_DOCTOR
SELECT * FROM DOCTOR;
--
ALTER TABLE DOCTOR
ADD CONSTRAINT PK_DOCTOR
PRIMARY KEY (DOCTOR_NO);
--
--NECESITO RELACIONAR DOCTORES CON HOSPITALES
SELECT * FROM HOSPITAL;
--
alter table DOCTOR
add constraint FK_DOCTOR_HOSPITAL
foreign key (HOSPITAL_COD)
references HOSPITAL(HOSPITAL_COD);
--TURNOS DE MAÑANA, TARDE O NOCHE (T,N,M)  
SELECT * FROM PLANTILLA;
ALTER TABLE PLANTILLA
ADD CONSTRAINT CH_PLANTILLA_TURNO
CHECK (TURNO IN('T','N','M'));
--
--
-UNA CLAVE PRIMARIA EN PROFESORES   PK_EN_HOSPITAL
ALTER TABLE HOSPITAL
ADD CONSTRAINT PK_HOSPITAL
PRIMARY KEY (HOSPITAL_COD);
--
--EJERCICIOS---
--
--TABLA COLEGIOS
--
CREATE TABLE COLEGIOS (
COD_COLEGIO NUMBER (9),
NOMBRE      VARCHAR2 (20) NOT NULLS,
LOCALIDAD   VARCHAR2 (15),
PROVINCIA   VARCHAR2 (15),
ANO_CONSTRUCCION  DATE,
COSTE_CONSTRUCCFION INTERGER,
CODE_REGION INTERGER,
UNICO INTERGER,   
PRIMARY KEY (COD_COLEGIO)
);
--
ALTER TABLE COLEGIOS
ADD CONSTRAINT CLAVE_UNICA_COLEGIO
UNIQUE (UNICO);
--
select * from COLEGIOS;
create sequence SEQ_COLEGIOS
increment by 10  
start with 0;
--
--TABLA PROFESORES
--
CREATE TABLE PROFESORES (
COD_PROFESOR VARCHAR2 (9) NOT NULLS,
NOMBRE      VARCHAR2 (20),
APELLIDO1   VARCHAR2 (15),
APELLIDO2   VARCHAR2 (15),
EDAD        NUMBER (3),
DNI         VARCHAR2 (09),
LOCALIDAD   VARCHAR2 (50), 
PROVINCIA   VARCHAR2 (50),   
SALARIO     INTERGER,
COD_COLEGIO NUMBER (9), 
PRIMARY KEY (COD_PROFESOR)
);
--
ALTER TABLE PROFESORES
ADD CONSTRAINT CLAVE_UNICA_PROF 
UNIQUE (DNI);
--
alter table PROFESORES
add constraint FK_PROFESORES_COLEGIOS
foreign key (COD_COLEGIO)
references COLEGIOS(COD_COLEGIO);
--
--TABLA REGIONES
--
CREATE TABLE REGIONES (
COD_REGION VARCHAR2 (9) NOT NULLS,
REGIONES   VARCHAR2 (20) NOT NULLS,
PRIMARY KEY (COD_REGION)
);
--
--
--TABLA ALUMNOS
--
CREATE TABLE ALUMNOS (
DNI VARCHAR2 (9) NOT NULLS,
NOMBRE VARCHAR2 (20) NOT NULLS,
APELLIDOS VARCHAR2 (50) 
FECHA_INGRESO DATE,
FECHA_NAC DATE,
LOCALIDAD VARCHAR2 (15),
PROVINCIA VARCHAR2 (30),
COD_COLEGIO NUMBER(9),
PRIMARY KEY (DNI)
);
--
alter table COLEGIOS
add constraint FK_COLEGIO_ALUMNOS
foreign key (COD_COLEGIO)
references ALUMNOS(COD_COLEGIO);
--
--
alter table REGION
add constraint FK_REGION_COLEGIO
foreign key (COD_REGION)
references ALUMNOS(COD_REGION);
--
--
ALTER TABLE PROFESORES
ADD (SEXO VARCHAR2(1), FECHA_NACIMIENTO DATE, ESTADO_CIVIL VARCHAR2 (15) NOT NULL);
--
--
ALTER TABLE PROFESORES
DROP COLUMN EDAD;
--
--
ALTER TABLE ALUMNOS
ADD (SEXO VARCHAR2(1), DIRECCION VARCHAR2(50), ESTADO_CIVIL VARCHAR2 (15) NOT NULL);
--
--
ALTER TABLE PROFESORES
DROP CONSTRAINT FK_PROFESORES_COLEGIOS;
--
--
ALTER TABLE ALUMNOS
MODIFY (FECHA_INGRESO SYSDATE);
--
--
INSERT INTO COLEGIO VALUES (1,'ABCDEFGHIJ','AEIOU');
INSERT INTO COLEGIO VALUES (1,'A','A');
INSERT INTO COLEGIO VALUES (1,'A','ABCDE');