select * from EMP;
-- LA MEJOR PRAXIS ES UTLIZAR EL NOMBRE DE LOS CAMPO DE LA TABLA
-- CONTROL + ENTER, EJECUTA LA LINEA EN LA CUAL ESTAMOS POSICIONADOS
select APELLIDO, OFICIO, SALARIO from EMP;
-- LA ORDENACION DE DATOS SIEMPRE ES ASCENDENTE
select * from EMP order by APELLIDO ASC;
-- ORDENACION DESCENDENTE DESC
select * from EMP order by APELLIDO DESC;
-- ORDENAR POR MAS DE UN CAMPO
select * from EMP order by DEPT_NO, OFICIO;
-- FILTRADO DE REGISTROS
-- OPERADORES DE COMPARACION
/* 
= igual
>= mayor o igual
<= menor o igual
> mayor
< menor
<> distinto
*/
-- Oracle, por defecto, difrenecia entre mayusculas y minusculas
-- en sus textos (string/varchar)
-- TODO LO QUE NO SE UN NUMERO SE ESCRIBE ENTRE COMMILAS SIMPLES '...'
-- PARA FLITAR SE UTLIZA LA PALABRA where Y SE ESCRIBE SOLAMENTE UNA VEZ DESPUES
-- DEL FROM
-- MOSTRAR TODOS LOS EMPLEADOS DEL DEPARTAMENTO 10
select * from EMP where DEPT_NO = 10;
-- mostrar todos los empleados cuyo oficio sea DIRECTOR
select * from EMP where OFICIO = 'DIRECTOR';
-- mostrar todos los empleados cuyo oficio sea DIFERENTE A DIRECTOR
select * from EMP where OFICIO <> 'DIRECTOR';
select * from EMP where OFICIO != 'DIRECTOR';
-- OPERADORES RELACIONALES
-- NOS PERMITEN REALIZAR MAS DE UNA PREGUNTA EN UNA CONSULTA
/*
OR ----> MUESTRA LOS DATOS DE CADA FILTRO
AND ---> TODOS LOS FILTROS DEBEN CUMPLIRSE
NOT ---> NEGACION DE UNA CONDICION (EVITARLO SIEMPRE)
*/
-- MOSTRAR LOS EMPLEADOS DEL DEPARTamento 10 y que tengan oficio director
select * from EMP where DEPT_NO = 10 AND OFICIO = 'DIRECTOR';
select * from EMP where DEPT_NO = 10 OR OFICIO = 'DIRECTOR';
-- Mostrar los valores del departamento 10 y el departamento 20
select * from EMP where DEPT_NO = 10 OR DEPT_NO = 20;
-- TENEMOS OTROS OPERADORES ADEMAS DE LOS STANDARD
-- BETWEEN MUESTRA LOS DATOS ENTRE UN RANGO INCLUSIVE
-- MOSTRAR LOS EMPLEADOS CUYOS SALARIO ESTE ENTRE 251000 Y 39000
select * from EMP where SALARIO between 251000 AND 390000 order by SALARIO;
-- PODEMOS HACER LA MISMA CONSULTA CON OPERADORES Y ES MAS EFICIENTE
select * from EMP where SALARIO >= 251000 AND SALARIO <=390000 order by SALARIO;
-- LA NEGACDION ES ALGO DE LO QUE DEBEMOS HUIR
-- MOSTRAR LOS EMPLEADOS QUE NO SEAN DIRECTOR
select * from EMP where NOT OFICIO = 'DIRECTOR';
-- PODEMOS REALIZAR LA MISMA CONSULTA CON OPERADOR
select * from EMP where OFICIO <> 'DIRECTOR';
-- EXISTE UN OPERADOR PARA BUSCAR COINCIDENCIAS EN TEXTOS
-- NOS PERMITE , MEDIANTE CARACTERES ESPECIALES HACER FILTROS EN TEXTOS
/*
% busca cualquier caracter y longitud
_ Un caracter cualquier 
? Un caracter nuemrico
*/
-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s
select * from EMP where APELLIDO LIKE '&s';
-- MOSTRAR LOS EMPLEADOS CUYO APELLIDO COMIENZA EN s Y FINALIZA CON a
select * from EMP where APELLIDO LIKE 's&a';
-- MOSTRAR TODOS LOS EMPLEADOS CUYO APELLIDO SE DE 4 LETRAS
select * from EMP where APELLIDO LIKE '____';
-- EXISTE OTRO OPERADOR PARA BUSCAR COINCIDENCIAS DE IGUALDAD EN UN MISMO
-- CAMPO: IN(valor1, valor2)
-- MOSTRAR LOS EMPLEADOS DEL DEPARTAMENTO 10, 20 Y 30, 55, 65, 77
select * from EMP where DEPT_NO = 10 OR DEPT_NO = 20;
OR DEPT_NO = 30 OR DEPT_NO = 55 OR DEPT_NO = 65 OR DEPT_NO = 77;
select * from EMP where DEPT_NO IN (10,20,30,55,65,77);
--MOSTRAR TODOS LOS EMPLEADOS QUE NO ESTEN EN EL DEPARTAMENTO 10 Y 20
select * from EMP where not DEPT_NO in (10,20); --NEGACION DE UNA CONDICION
select * from EMP where DEPT_NO not in (10,20); --NEGACION      
-- UN CAMPO CALCULADO ES UNA HERRAMIENTA EN UNA CONSULTA
-- SIRVE PARA GENERAR CAMPOS QUE NO EXISTAN EN LA TABLA Y LOS PODEMOS CALCULAR
-- MOSTRAR EL APELLIDO, EL SALARIO, COMISION Y 
-- EL SALARIO TOTAL (SALARIO + COMSION)
-- de todos los empleados cuyo salario mas comision sea mayor a 344500
-- UN CAMPO CALCULADO SOLO ES PARA EL CURSOR
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION ) as TOTAL from EMP
where ( SALARIO + COMISION ) >= 344500;
-- ESTA CONSULTA ESTAMOS GENERANDO UN CURSOR LA CUAL ES LA CONSULTA GENERADA
-- QUEREMOS LA CONSULTA ORIGINAL YORDENAR POR ELLA
select APELLIDO, SALARIO, COMISION, (SALARIO + COMISION ) as TOTAL from EMP
order by TOTAL;
-- CLAUSULA DISTINCT: SE UTILIZA PARA EL SELECT Y LO QUE REALIZA ES
-- ELIMINAR REPETIDOS DE LA CONSULTA
-- MOSTRAR EL OFICIO DE LOS EMPLEADOS
select distinct OFICIO from EMP;
-- MOSTRAR LOS DIFERENTES OFICIOS , APALLIDOS DE LOS EMPLEADOS, UN SIN SENTIDO...
select distinct OFICIO, APELLIDO from EMP;
--
--
-- PRACTICA
--
--
-- TABLA:ENFERMOS NACIDOS ANTES 11/01/1970 
SELECT * FROM ENFERMO;
--
-- DESCRIPCION DE LOS CAMPOS DE LA TABLA
DESC ENFERMO;
--
select INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, SEXO, NSS from ENFERMO
where FECHA_NAC <= '11/01/1970';
--
-- TABLA:ENFERMOS Nacidos antes del 1/1/1970 ordenados por número de inscripción.
select INSCRIPCION, APELLIDO, DIRECCION, FECHA_NAC, SEXO, NSS from ENFERMO
where FECHA_NAC <= '01/01/1970' order by INSCRIPCION;
--
-- Listar todos los datos de la plantilla del hospital del turno de mañana
select  distinct turno from PLANTILLA;
select HOSPITAL_COD, SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO,
SALARIO FROM PLANTILLA
WHERE TURNO = 'M';
--
--Idem del turno de noche. 
select HOSPITAL_COD, SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO,
SALARIO FROM PLANTILLA
WHERE TURNO = 'N';
--
--Listar los doctores que su salario anual supere 3.000.000 €. 
--
select HOSPITAL_COD, DOCTOR_NO, APELLIDO, ESPECIALIDAD, SALARIO, (SALARIO * 12)AS SALARIOANUAL   
FROM DOCTOR 
WHERE (SALARIO * 12) > 3000000;
-- 
--Visualizar los empleados de la plantilla del turno de mañana que tengan un salario entre 2.000.000 y 2.250.000. 
SELECT SALARIO  FROM PLANTILLA WHERE TURNO = 'M';
select HOSPITAL_COD, SALA_COD, EMPLEADO_NO, APELLIDO, FUNCION, TURNO,
SALARIO FROM PLANTILLA
WHERE TURNO = 'M' AND 
SALARIO >= 200000 AND SALARIO <= 225000;
--
--Visualizar los empleados de la tabla emp que no se dieron de alta entre el 01/01/1980 y el 12/12/1982. 
SELECT distinct FECHA_ALT FROM EMP;
select EMP_NO, APELLIDO, OFICIO, DIR, FECHA_ALT, SALARIO, COMISION, DEPT_NO from EMP
WHERE FECHA_ALT >= '01/01/1980' AND FECHA_ALT <= '12/12/1982';
--
--Mostrar los nombres de los departamentos situados en Madrid o en Barcelona. 
SELECT LOC FROM DEPT;
select DEPT_NO, DNOMBRE, LOC FROM DEPT
WHERE LOC IN ('MADRID','BARCELONA');
--
--
--CONSULTAS DE AGRUPACION
--
--
-- ESTE TIPO DE CONSULTAS NOS PERMITEN MOSTRAR ALGUN RESUMEN
-- SOBRE UN GRUPO DETERMINADO DE DATOS
-- UTILIZAN FUNCIONES DE AGRUPACION PARA CONSEGUIR EL RESUMEN
-- LAS FUNCIONES DEBEN TENER ALIAS
-- COUNT(*): CUENTA EL NUMERO DE REGISTROS INCLUYENDO NULOS
-- COUNT(CAMPO): CUENTA EL NUMERO DE REGISTROS SIN NULOS
-- SUM(NUMERO): SUMA EL TOTAL DE UN CAMPO NUMERO
-- AVG(NUMERO): RECUPERA LA MEDIA DE UN CASMPO NUMERICO
-- MAX(CAMPO): DEVUELVE EL MAXIMO VALOR DE UN CAMPO
-- MIN(NUMERO): DEVUELVE EL MINIMO VALOR DE UN CAMPO 
-- MOSTRAR EL NUMERO DE REGISTRO DE LA TABLA DOCTOR
--
select count(*) AS NUMERO_DOCTORES from DOCTOR; 
SELECT COUNT(APELLIDO) AS NUMERO_DOCTORES from DOCTOR;
--
-- SE PUEDEN COMBINAS VARIAS FUNCIONES
-- QUEREMOS EL NUMERO DE DOCTORES CON EL MAXIMO SALARIO
select count(*) as DOCTORES, MAX(salario) as MAXIMO from DOCTOR;
-- LOS CAMPOS RESULTANTES DE LAS FUNCIONES PODEMOS AGRUPARLOS POR
-- ALGUN CAMPO/S DE LA TABLA
-- CUANDO QUEREMOS AGRUPAR UTILIZAMOS  group by DESPUES DEL from
-- TRUCO: DEBEMOS AGRUPAR POR CADA CAMPO QUE NO SEA UNA FUNCION
-- MOSTRAR CUANTOS DOCTORES EXISTEN POR CADA ESPECIALIDAD
select count(*)as DOCTORES, ESPECIALIDAD
from DOCTOR
group by ESPECIALIDAD; 
--
-- MOSTRAR NUMERO DE PERSONAS Y MAXIMO SALARIO DE LOS EMPLEADOS
-- POR CADA DEPARTAMENTO OFICIO
select count(*)as PERSONAS, max(SALARIO) AS MAXIMO_SALARIO, DEPT_NO, OFICIO
FROM EMP
group by DEPT_NO, OFICIO;

--FILTRANDO EN CONSULTAS DE AGRUPACION
-- TENEMOS DOS POSIBILIDADES
-- WHERE: ANTES DEL GROUP BY
-- HAVING: DESPUES DEL GROUP BY
-- MOSTRAR CUEANTO SEMPLEADOS TENEMOS POR CADA OFICIO
-- QUE COBREN MAS DE 200000
-- HAVING FILTRADO EN EL SELECT (CONJUNTO9
-- WHERE FLITRADOR POR CAMPOS DE LA TABLA 
SELECT COUNT(*) AS EMPLEADOS, OFICIO
FROM EMP
WHERE SALARIO > 200000
group by OFICIO;
--
--MUCHOS REGISTROS
--
SELECT COUNT(*) AS EMPLEADOS, OFICIO
FROM EMP
WHERE OFICIO IN ('ANALISTA','VENDEDOR')
group by OFICIO;
--
SELECT COUNT(*) AS EMPLEADOS, OFICIO
FROM EMP
WHERE OFICIO IN ('ANALISTA','VENDEDOR')
group by OFICIO;
--
SELECT COUNT(*) AS EMPLEADOS, OFICIO
FROM EMP
group by OFICIO;
having count(*) > 2;
